
/** generated by createManifest.js **/
module.exports = {
    get: () => {
        return {
          allActions: {
            Cart: require('components/Mendies/Cart/actions').default,
            Header: require('components/Mendies/Header/actions').default,
            Categories: require('components/Mendies/Pages/Categories/actions').default,
            Category: require('components/Mendies/Pages/Category/actions').default,
            Home: require('components/Mendies/Pages/Home/actions').default,
            ProductDetail: require('components/Mendies/Pages/ProductDetail/actions').default,
            Router: require('reactium-core/components/Router/actions').default,
            Toolkit: require('reactium-core/components/Toolkit/actions').default,
          },
          allActionTypes: {
            Cart: require('components/Mendies/Cart/actionTypes').default,
            Header: require('components/Mendies/Header/actionTypes').default,
            Categories: require('components/Mendies/Pages/Categories/actionTypes').default,
            Category: require('components/Mendies/Pages/Category/actionTypes').default,
            Home: require('components/Mendies/Pages/Home/actionTypes').default,
            ProductDetail: require('components/Mendies/Pages/ProductDetail/actionTypes').default,
            Router: require('reactium-core/components/Router/actionTypes').default,
            Toolkit: require('reactium-core/components/Toolkit/actionTypes').default,
          },
          allReducers: {
            Cart: require('components/Mendies/Cart/reducers').default,
            Header: require('components/Mendies/Header/reducers').default,
            Categories: require('components/Mendies/Pages/Categories/reducers').default,
            Category: require('components/Mendies/Pages/Category/reducers').default,
            Home: require('components/Mendies/Pages/Home/reducers').default,
            ProductDetail: require('components/Mendies/Pages/ProductDetail/reducers').default,
            Router: require('reactium-core/components/Router/reducers').default,
            Toolkit: require('reactium-core/components/Toolkit/reducers').default,
          },
          allInitialStates: {
            Cart: require('components/Mendies/Cart/state').default,
            Header: require('components/Mendies/Header/state').default,
            Categories: require('components/Mendies/Pages/Categories/state').default,
            Category: require('components/Mendies/Pages/Category/state').default,
            Home: require('components/Mendies/Pages/Home/state').default,
            ProductDetail: require('components/Mendies/Pages/ProductDetail/state').default,
            Router: require('reactium-core/components/Router/state').default,
            Toolkit: require('reactium-core/components/Toolkit/state').default,
          },
          allRoutes: {
            Cart: require('components/Mendies/Cart/route').default,
            Categories: require('components/Mendies/Pages/Categories/route').default,
            Category: require('components/Mendies/Pages/Category/route').default,
            Home: require('components/Mendies/Pages/Home/route').default,
            ProductDetail: require('components/Mendies/Pages/ProductDetail/route').default,
            Toolkit: require('reactium-core/components/Toolkit/route').default,
          },
          allServices: {
            Cart: require('components/Mendies/Cart/services').default,
            Header: require('components/Mendies/Header/services').default,
            Categories: require('components/Mendies/Pages/Categories/services').default,
            Category: require('components/Mendies/Pages/Category/services').default,
            Home: require('components/Mendies/Pages/Home/services').default,
            ProductDetail: require('components/Mendies/Pages/ProductDetail/services').default,
            Toolkit: require('reactium-core/components/Toolkit/services').default,
          },
          allMiddleware: {
            redux: require('reactium-core/redux/middleware').default,
          },
          allEnhancers: {
            redux: require('reactium-core/redux/enhancer').default,
          },

        }
    },
    list: () => {
        return {
  "allActions": {
    "type": "actions",
    "imports": [
      "components/Mendies/Cart/actions",
      "components/Mendies/Header/actions",
      "components/Mendies/Pages/Categories/actions",
      "components/Mendies/Pages/Category/actions",
      "components/Mendies/Pages/Home/actions",
      "components/Mendies/Pages/ProductDetail/actions",
      "reactium-core/components/Router/actions",
      "reactium-core/components/Toolkit/actions"
    ]
  },
  "allActionTypes": {
    "type": "actionTypes",
    "imports": [
      "components/Mendies/Cart/actionTypes",
      "components/Mendies/Header/actionTypes",
      "components/Mendies/Pages/Categories/actionTypes",
      "components/Mendies/Pages/Category/actionTypes",
      "components/Mendies/Pages/Home/actionTypes",
      "components/Mendies/Pages/ProductDetail/actionTypes",
      "reactium-core/components/Router/actionTypes",
      "reactium-core/components/Toolkit/actionTypes"
    ]
  },
  "allReducers": {
    "type": "reducers",
    "imports": [
      "components/Mendies/Cart/reducers",
      "components/Mendies/Header/reducers",
      "components/Mendies/Pages/Categories/reducers",
      "components/Mendies/Pages/Category/reducers",
      "components/Mendies/Pages/Home/reducers",
      "components/Mendies/Pages/ProductDetail/reducers",
      "reactium-core/components/Router/reducers",
      "reactium-core/components/Toolkit/reducers"
    ]
  },
  "allInitialStates": {
    "type": "state",
    "imports": [
      "components/Mendies/Cart/state",
      "components/Mendies/Header/state",
      "components/Mendies/Pages/Categories/state",
      "components/Mendies/Pages/Category/state",
      "components/Mendies/Pages/Home/state",
      "components/Mendies/Pages/ProductDetail/state",
      "reactium-core/components/Router/state",
      "reactium-core/components/Toolkit/state"
    ]
  },
  "allRoutes": {
    "type": "route",
    "imports": [
      "components/Mendies/Cart/route",
      "components/Mendies/Pages/Categories/route",
      "components/Mendies/Pages/Category/route",
      "components/Mendies/Pages/Home/route",
      "components/Mendies/Pages/ProductDetail/route",
      "reactium-core/components/Toolkit/route"
    ]
  },
  "allServices": {
    "type": "services",
    "imports": [
      "components/Mendies/Cart/services",
      "components/Mendies/Header/services",
      "components/Mendies/Pages/Categories/services",
      "components/Mendies/Pages/Category/services",
      "components/Mendies/Pages/Home/services",
      "components/Mendies/Pages/ProductDetail/services",
      "reactium-core/components/Toolkit/services"
    ]
  },
  "allMiddleware": {
    "type": "middleware",
    "imports": [
      "reactium-core/redux/middleware"
    ]
  },
  "allEnhancers": {
    "type": "enhancer",
    "imports": [
      "reactium-core/redux/enhancer"
    ]
  }
};
    }
}
